# Default values for mmli-oed-api
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# Arbitrary configuration, unique to this application
config:
  # Defined as an encrypted SealedSecret (see below)
  # NOTE: This overrides the hardcoded values below
  existingSecret: moldb-cleandb-api

  # Alternatively, you can hardcode the values here instead (for local development only)
  # These are ignored if existingSecret is defined above
  CLEAN_DB_USER: 'molfront'
  CLEAN_DB_PASSWORD: ''   # See SealedSecret below
  CLEAN_DB_HOST: 'moldb-postgres-ro.moldb.svc.cluster.local'
  CLEAN_DB_PORT: '5432'
  CLEAN_DB_NAME: 'molfront'


# The Deployment captures everything about the container that will run
controller:
  # Define how many replicas of this application should run
  replicas: 1

  # Define which Docker image should be run for this application (container)
  image:
    repository: moleculemaker/mmli-cleandb-api
    pullPolicy: Always
    #pullSecrets: []

  # TODO: parameterize labels, tolerations, nodeSelector, resources, etc?


# Define how to access this application over the network
# The Service creates a static IP that will round-robin requests to the different replicas
service:
  type: ClusterIP
  protocol: TCP
  port: 8000


# Define whether / how to access this application over the public internet
ingress:
  enabled: true
  hostname: "fastapi.cleandb.mmli1.ncsa.illinois.edu"
  tls: true
  className: traefik
  annotations:
    # Automatically issue a TLS certificate for this ingress hostname
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production

    # Define Traefik strict TLS rules and Middlewares for ForwardAuth
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"

    # No keycloak group auth:
    traefik.ingress.kubernetes.io/router.middlewares: openenzymedb-oed-staging-cors-header@kubernetescrd

    # For keycloak group auth:
    #traefik.ingress.kubernetes.io/router.middlewares: openenzymedb-oed-staging-cors-header@kubernetescrd,openenzymedb-oed-staging-redirect-to-login@kubernetescrd,openenzymedb-oed-staging-private-auth@kubernetescrd


# TODO: in the future if this is split into prod/staging, this secret would likely be for staging
# Additional Kubernetes resources to deploy along with this Helm chart
# SealedSecrets, Middlewares, Volume definitions, etc
extraDeploy:
  # First, we build up in plaintext the Secret that we would like to encrypt (seal)
  # After building up a raw Secret, the cluster admin can encrypt them using the following command:
  #     kubeseal --format yaml < mmli-cleandb-api.moldb.secret.yaml > mmli-cleandb-api.moldb.sealedsecret.yaml
  # SealedSecrets can only be decrypted (unsealed) by our cluster's private key
  # This Secret will be automatically decrypted by our cluster, making it available to our application
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: moldb-cleandb-api
      namespace: openenzymedb
    spec:
      encryptedData:
        CLEAN_DB_HOST: AgAo9iqzHnZqnxxhxPSwqIuVNco3pe2iY9FsR5e4TZx2OTMEBgqNFSh7ketjk5Gevlr0wTWIkTdq9AVaCJnVfMvGk+chh00w27CvvKtoE2c68NpWyYM7bYuKjv9Lg2CrvzbyXvvNEiNrAhyuc9EGb3ASoiJTbcUn1cjHZDTX6cmdmwX7hDYgX7CHqLREhLhO0dMtIEC/zgrWfAxVIq5LNjc91g9KOQoggDkXpD+TFjuRMB4tOv8KYw6+O2cYrDAlqb6l1L8T8NarTDUSM3y/4zcmF5Ps2lXnF6fB09axDhG2z0EvAsBs3uAAQ1njzx8atJ6H7FaCxVqHWy8vmUBnEu0xTJIevoTMZCSfwUwvcrJCPppV7ER8WsV7FMvH2t916/RGlY0rdP7qchMGtyMEomZJkQ0gX/gxt8CCD6j7vRFAedoKcNEjXKsY3HgUJ9bTxZc5LK9CBSScJjE2ACerBrKNqU4EsfrX3svuyCs4v4mSaEVgd4z67QE0CIZdhR0WLyxXxpwYftzzOSS9p46E1RVk9qzu3nYGl90YjXrj+CPY5CVAdTBe8+hy5MrF4jbHhCz/XzTuMFBukrUVwmyvquFP0w5FdsSaC1tggF6NTM5r8DsE7fZHr0CDGnmMiItcuIg0OC48F6IFbgMlWVjVSZs3hJc3EyAZVx110NUJaoZLFMq2vB39Oo/3EXZBuQPRvQDnkBzU1tRTMRvqE6nR7Ay4B6OIdo9C7koZJdwYeUz3lH+D2lrDl0k1tw==
        CLEAN_DB_NAME: AgB7mb/up6VOUA91jbgXBFmyDbwiu2mqdVgMI+Wl9pu6DNcgAqqY7WE6ye+C4x4bf3gAA9XIuv7VKfGtINWZUm932zYrZ8T7tEvuLR4RV6iR2gLeRr8Yapw3rYTWMmSJfWMZAHM5pgAgOeffOWFv3N+HJlUyJelhDn6JXcs4S8pK7TDkx1MxFklI2lP0uzgqv2UESYoknnU9YToYabczNEcbUCJgVGgqZV+2SqH/3khnRSorJTf3XCAg6/5k+W4v03CrcJASnbCpLGAp8bl1XZljBM9EX9BxTR4POb8NtFtg8I+0E04P7pb0m1TKTAzGuWTyJrq/kmKWcO8o3chwhjOYZHgli7NEoBHxglwPDtYATeTrJQliJyizupe7cpH0OPnb0PjhMdmkMcLpyL9DvyclHQNKKOvgQQ78s4PlFaKYrfwDk735t7OE4LYL5jilWZZ+J6Wmi7bwuhzbPXJF90rnW9LKqO3A8gay/wczIkaZ8Mv+RrR57ZuEMLxRnJht7PswCQobZo0qGC3qnPS+pWUGXE4FUBb9aOlF86xe08l19UJpVBhF86+uy9IeJqdlXa5jXA2iHRS5X5oYmHK2ObiFemDREFOTL2UAcNAgkGvXrwy0KeJfUaFnSPNe62FUuTexG90SKQF81l+LhAjvhWXaEEfHxMrWGsSBhEAZ0HgvSjYP6g/oxrNAx2VLuD53Rn8XW3dvVGPExQ==
        CLEAN_DB_PASSWORD: AgCC55Ukf+lUC6xSerdT0oLjHv/VljB/0ULt4dPkF7kqIgvLPNEamjHOvuIy514ChRbCsw2SWdoWJbPJYbck1+TGf1uphgfYEykvsVxiapLmXmspagYSZSzvu0nvOebQBiq1wDtLEQxO1av4Vo9futc8EJf9cyFGBLL2FhBTymolaZIMYAqfl0x9IjonRR7/aafQJRC51++0qvAiZUlT6Xn1wGgNYivG3VlEMjKZ3MantdWJcy3IXAoxeJvpsfhtNp5ud+cbSsC2dD+qMdnX77Qxl96h41xOXQS6elwyn3lmBn3xzm7JfHRO5ErWBeTsNhMxNnS24ozHE1T8wlOjCF6AGykOJC51dxeDHeXrQfIX4SkQsCu+FmzS6yHFGAJQqaDQerKgi8+Y0CTWTU5vsigXGM651F6RVGb8dB1017ByJFikgMRhkPug2mjo/tPwWHBNAJNp5ydyVzpWivUYxFHoGrTCWmOE/aDJ/A/iiwPi6bKLtX73eFWn2ouUWkqzPxccNC45PqsogCfOVkQX8F0dQtvh8OvLXhvNgwFuKs+LGnyALX73UECybDCU2IjbQRBWTebzJC9QtJBP3P+2c+AX0NSHPdn5jVDLi/+F0z/iKBC0f9ptLjYaiyO+mgXI923CJb28jMwRJBXxpAIeZE6kNmI73NfFpO0fhJAnwkd/YhJJL8BdcHbX5uu0H3ux+5jtVu+yOYF4KSlI3ux4A0lG06sgysqBBfFrxPDRYVSlcQ==
        CLEAN_DB_PORT: AgA9u35MRsfabJ+I6M0Nrfz2YHrVa1RaDIQXO47MMJ/M/gx4vKNx4hY4qXjO/zgN+LE5/Txbyh8h5otemAkQ5uM/7p9LCKHfGtM8kClTM6MZlnnQxwjcjP+HJkBPw/Pi2etvO3NYfcTXTLoGCODSxvOW6Vcbuf6VGteLeRieEUskO0CC4Lk4duajBbbnfMjCl0T//8yti33RwjgwoBSItxOWIHIyZb1jhijP4feIwORYqW72jR8Q1BYYrTMDLlLnrC+EoLKHfyitqGk7P6fK4uoBF2kpbI97jsJqTpFtD69LdGl0FpqKQpSGGIqyLmmW1BcfEm6Umrvry9zkNBXukZVOgPGFj95NrndxKzt5P+TWvpDxoq9t8wC5rZQDBlwqLWgViH+OKwOGoUz2YLal4d0GxjlhObJYSh7PJPQvS1Hhm1uQQ5iS9nrsdD5nPSMNnJAhu8JS65h5TR3d73ZVMcV7mhY3I1rqShxsuUuC8pBk9NiqDiLX3jOmNCaBnJTos54OqMSeLlDCL26OACIiKE/H7M7UwuzZbZ9RC7LGA0INrJwbIppS3gAtyacekB6XNO1VdrPg42XdlwFoUtm8W/g1y2BruwIMv4AkHkMgPF05V9Vm+ZV3hclTRk+SXFnFcKJVi84ROi3fvgSNNBQwXirBNta615TnQ8LLm9FZIPDAiReNUwkLvdX4gWDm2EJ7X4azVHxC
        CLEAN_DB_USER: AgB1NmKHFxexaE+ZXvIQw7EgCY+9jyMK9cC/YMkkMuZ32PGmazO0p1kOIQPm1SJJJE8NRHgNUTCAvVs5eyKcdV1tyCgGfYfiKCpnh/xFMKENqUXIiBffptiHHE3AXwS/vGPRl23r0kGBlnvpt7WLma/IWFTy9ZmF0UEgKvh8Y0tOkTreOg3MKw2j/H/a2G4cUl/hJJPEsj/L8UR3HRQ6jiEoyw5jOQGHvApXkeTTuYFNILDm0Y/7VcZ8+Kt3LW901WqpVdx3g4Oq/ia5UkyS9DIGJLbSsU2aBBlS0S2dUh41iTw/oxYMnX08lIQytHSE3LgszbuhwhDdX5ibDOpRgfYjyOfg8jVwIpPZDsZBhAn4o2nn2qp4wjWGvj8+baM5TvJP7J0SyNYN8labJchj+04OLzFS7kDkjQoWqcBE/AToN5Zh9R39eEt+By8pkxPsn/3hTUa+QsSBAptU+GrY2C4gEG1u6HYLlQ5jyYGx/vgYPNyRUnv4OXarMl+12KH0/1rfd/vVJmS3BoQmHjxGVx1A8O1Mumt1THUwOx9MV/S9MxMPKTk/C9X4pwKBjwDHkrhFhvi3cGg90ytNM+P3Yzvi7rLzHAfNB0Wph8NByodEBakQjehI5GJHkSstPeI4DCDear8y7sXIgXCJN7DY3/xaQnK09xhGsygklCpDfn5i1FeR9rSMm6NZUnI80Cd1Mi78hhMo2WDi5Q==
        DATABASE_URL: AgBd9w9cNQ30CB1/pJ8oyTvcs0yymvvK/xCb2SLfjoPeRDJjX75T0IrkE+7dnY07Tl1GIoFO4D66wbYjyo7U9Mcq4iOYUi5cFVFOcvHhflYV0mA3pTihBiechuTWCkhhYRfWIBjOz0v7TRCzj58aKWUV7OQBMk9iKBJ19CPzLM2aGB9SOFsV4Yb5Mt/Rjb4vZz8sFXzhF7rjl+sQJLC6jb83Yerv8S14dlsgbVP3+U1QToE/Y9IfcH3JSapp7kXip63vv5lAY8EmIfgrdbgfyqLCKniXJMRMwb3bpSrGtq1DMnScJ7Tv3Gdjz4ImQ/VfTVG21UXmO8YQAj4BkIQ6vnm6reAUWd1Jb4mNrqp7gct50XKF/bY1iY3Brp7PoB7xvwD5T2I/oDJ4AVwaXVRn/kDyeINMK9TVHa5k+ccMvcjGTPyJccPQmUj/X0AWxYBmqDrlRqzyWrlXMRWyIkCFUE/Q1sSYLrTZOd7qjgucoK+fEXaFupUxe7CVKdEraH1QJjAoKcxc1rEeUFBME2DKkMZSZo2IAkjPoppnRTDZpffHls9DjwjQ7k42EiAXVmMiSHYjJSDobh4esMfMtCFuquUB88e41++X8VnvTvq5EGjP4xxOLLjJbDNT1CXccA0eJsMMIBkcL0etP2xlV/qxszhcjggu60igYobKPelEvFez8rcp5mpnPODQc3b47MIn1qmMmhRJHel3x1BZzfIaPvYDTdRtVfyTVm2nEEKcPd2kiuHextERhbW6gBUIFEMQeG9kWSkEgie1LRyjsom1MEDjCRAWKtV+ecXm37mtTrR0o+9185fAe4PkGmO5djuotlvC5mOvIPXdG/6vKJk=
      template:
        metadata:
          creationTimestamp: null
          name: moldb-cleandb-api
          namespace: openenzymedb
        type: Opaque
